stages:
  preprocess:
    cmd: python -m vehicle_emissions.preprocessing.clean_data --full

    deps:
      - src/vehicle_emissions/preprocessing/clean_data.py
      - data/raw/data_2024.csv

    outs:
      - data/processed/data_2024_cleaned.csv

  feature_engineering:
    cmd: python -m vehicle_emissions.features.build_features --full

    deps:
      - src/vehicle_emissions/features/build_features.py
      - data/processed/data_2024_cleaned.csv

    outs:
      - data/interim/data_2024_features.csv


  train_test_preprocessing:
    cmd: python -m vehicle_emissions.preprocessing.train_test_preprocessing --full

    deps:
      - src/vehicle_emissions/preprocessing/train_test_preprocessing.py
      - data/interim/data_2024_features.csv

    outs:
      - data/processed/X_train_processed.parquet
      - data/processed/X_test_processed.parquet
      - data/processed/y_train.parquet
      - data/processed/y_test.parquet
      - models/preprocessing/imputation_values.joblib
      - models/preprocessing/onehot_encoder.joblib
      - models/preprocessing/standard_scaler.joblib
      - models/preprocessing/preprocessing_metadata.json
  
  
  train_regression_model:
    cmd: python -m vehicle_emissions.training.train_regression_model --full

    deps:
      - src/vehicle_emissions/training/train_regression_model.py
      - models/metadata/random_forest_regression_metadata.json
      - data/processed/X_train_processed.parquet
      - data/processed/X_test_processed.parquet
      - data/processed/y_train.parquet
      - data/processed/y_test.parquet

    outs:
      - models/trained/random_forest_regressor.joblib
      - models/trained/random_forest_regressor_training_metadata.json
  

  train_classification_model:
    cmd: python -m vehicle_emissions.training.train_classification_model --full

    deps:
      - src/vehicle_emissions/training/train_classification_model.py
      - models/metadata/random_forest_classification_metadata.json
      - data/processed/X_train_processed.parquet
      - data/processed/X_test_processed.parquet
      - data/processed/y_train.parquet
      - data/processed/y_test.parquet

    outs:
      - models/trained/random_forest_classifier.joblib
      - models/trained/random_forest_classifier_training_metadata.json